#docker run --name nodejs -it  -p 3000:3000 bulletinboard:1.0 bash
FROM node:12

# создание директории приложения
WORKDIR /usr/src/app

# установка зависимостей
# символ астериск ("*") используется для того чтобы по возможности 
# скопировать оба файла: package.json и package-lock.json
COPY ./ ./

RUN npm install
# Если вы создаете сборку для продакшн
# RUN npm ci --only=production



EXPOSE 3000
CMD [ "npm", "start" ]
